services:
    eliza:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - eliza:/app/packages/client-twitter/src/tweetcache
            - eliza:/app/db.sqlite
        environment:
            - OPENAI_API_KEY=
            - PRIVY_APP_ID=
            - PRIVY_APP_SECRET=
            - PRIVY_SAFE_OWNER_ID=
            - PRIVY_SESSION_OWNER_ID=
            - PRIVY_AUTHORIZATION_PRIVATE_KEY=
            - ETHEREUM_PROVIDER_ODYSSEYTESTNET=
            # Refer to: https://github.com/elizaOS/eliza/blob/develop/.env.example for all available environment variables
        ports:
            - "3000:3000"
            - "5173:5173"
        restart: always

volumes:
    eliza:
